directive @length(
  min: Int = UNDEFINED,
  max: Int = UNDEFINED
) on | INPUT_FIELD_DEFINITION

directive @isAuthenticated on QUERY | FIELD_DEFINITION

type User {
  id: ID!
  username: String!
  password: String!
  email: String!
  firstName: String!
  lastName: String!
  rank: String!
  isActive: String!
  createdAt: String!
  updatedAt: String!
}

input userCreateInput {
  username: String! @length(min: 3, max: 10)
  password: String!
  firstName: String!
  lastName: String!
  email: String!
}

type Query {
  users: [User]
  user(id: Int!): User
}

type Mutation {
  userCreate(input: userCreateInput): User
}
