type User {
  id: ID!
  username: String!
  password: String!
  email: String!
  firstName: String!
  lastName: String!
  rank: String!
  isActive: Boolean!
  createdAt: String!
  updatedAt: String!
}

extend type Query {
  users: [User]
  user(id: Int!): User
}

input userCreateInput {
  username: String!
  password: String!
  firstName: String!
  lastName: String!
  email: String!
}

extend type Mutation {
  userCreate(input: userCreateInput): User
}
